(define (problem drone_problem_d6_r6_l10_p10_c10_g10_ct2)
(:domain drone-dom)
(:objects
	drone1 - drone
	drone2 - drone
	drone3 - drone
	drone4 - drone
	drone5 - drone
	drone6 - drone
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	box1 - box
	box2 - box
	box3 - box
	box4 - box
	box5 - box
	box6 - box
	box7 - box
	box8 - box
	box9 - box
	box10 - box
	food - content
	meds - content
	human1 - human
	human2 - human
	human3 - human
	human4 - human
	human5 - human
	human6 - human
	human7 - human
	human8 - human
	human9 - human
	human10 - human
	carrier1 - carrier
	carrier2 - carrier
	carrier3 - carrier
	carrier4 - carrier
	carrier5 - carrier
	carrier6 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(carrier-at carrier1 warehouse)
	(carrier-n-boxes carrier1 n0)
	(carrier-drone-free carrier1)
	(carrier-at carrier2 warehouse)
	(carrier-n-boxes carrier2 n0)
	(carrier-drone-free carrier2)
	(carrier-at carrier3 warehouse)
	(carrier-n-boxes carrier3 n0)
	(carrier-drone-free carrier3)
	(carrier-at carrier4 warehouse)
	(carrier-n-boxes carrier4 n0)
	(carrier-drone-free carrier4)
	(carrier-at carrier5 warehouse)
	(carrier-n-boxes carrier5 n0)
	(carrier-drone-free carrier5)
	(carrier-at carrier6 warehouse)
	(carrier-n-boxes carrier6 n0)
	(carrier-drone-free carrier6)
	(drone-at drone1 warehouse)
	(drone-free drone1)
	(drone-at drone2 warehouse)
	(drone-free drone2)
	(drone-at drone3 warehouse)
	(drone-free drone3)
	(drone-at drone4 warehouse)
	(drone-free drone4)
	(drone-at drone5 warehouse)
	(drone-free drone5)
	(drone-at drone6 warehouse)
	(drone-free drone6)
	(box-at box1 warehouse)
	(box-free box1)
	(box-at box2 warehouse)
	(box-free box2)
	(box-at box3 warehouse)
	(box-free box3)
	(box-at box4 warehouse)
	(box-free box4)
	(box-at box5 warehouse)
	(box-free box5)
	(box-at box6 warehouse)
	(box-free box6)
	(box-at box7 warehouse)
	(box-free box7)
	(box-at box8 warehouse)
	(box-free box8)
	(box-at box9 warehouse)
	(box-free box9)
	(box-at box10 warehouse)
	(box-free box10)
	(box-has box1 food)
	(box-has box2 food)
	(box-has box3 food)
	(box-has box4 food)
	(box-has box5 food)
	(box-has box6 food)
	(box-has box7 food)
	(box-has box8 meds)
	(box-has box9 meds)
	(box-has box10 meds)
	(human-at human1 loc6)
	(human-free human1)
	(human-at human2 loc8)
	(human-free human2)
	(human-at human3 loc5)
	(human-free human3)
	(human-at human4 loc4)
	(human-free human4)
	(human-at human5 loc4)
	(human-free human5)
	(human-at human6 loc6)
	(human-free human6)
	(human-at human7 loc1)
	(human-free human7)
	(human-at human8 loc6)
	(human-free human8)
	(human-at human9 loc6)
	(human-free human9)
	(human-at human10 loc6)
	(human-free human10)
	(next n0 n1)
	(next n1 n2)
	(next n2 n3)
	(next n3 n4)
	(= (fly-cost warehouse warehouse) 0)
	(= (fly-cost warehouse loc1) 8)
	(= (fly-cost warehouse loc2) 28)
	(= (fly-cost warehouse loc3) 37)
	(= (fly-cost warehouse loc4) 46)
	(= (fly-cost warehouse loc5) 22)
	(= (fly-cost warehouse loc6) 38)
	(= (fly-cost warehouse loc7) 3)
	(= (fly-cost warehouse loc8) 33)
	(= (fly-cost warehouse loc9) 7)
	(= (fly-cost warehouse loc10) 18)
	(= (fly-cost loc1 warehouse) 33)
	(= (fly-cost loc1 loc1) 0)
	(= (fly-cost loc1 loc2) 12)
	(= (fly-cost loc1 loc3) 8)
	(= (fly-cost loc1 loc4) 34)
	(= (fly-cost loc1 loc5) 16)
	(= (fly-cost loc1 loc6) 37)
	(= (fly-cost loc1 loc7) 38)
	(= (fly-cost loc1 loc8) 1)
	(= (fly-cost loc1 loc9) 5)
	(= (fly-cost loc1 loc10) 1)
	(= (fly-cost loc2 warehouse) 39)
	(= (fly-cost loc2 loc1) 26)
	(= (fly-cost loc2 loc2) 0)
	(= (fly-cost loc2 loc3) 44)
	(= (fly-cost loc2 loc4) 50)
	(= (fly-cost loc2 loc5) 40)
	(= (fly-cost loc2 loc6) 20)
	(= (fly-cost loc2 loc7) 49)
	(= (fly-cost loc2 loc8) 18)
	(= (fly-cost loc2 loc9) 17)
	(= (fly-cost loc2 loc10) 49)
	(= (fly-cost loc3 warehouse) 11)
	(= (fly-cost loc3 loc1) 12)
	(= (fly-cost loc3 loc2) 21)
	(= (fly-cost loc3 loc3) 0)
	(= (fly-cost loc3 loc4) 42)
	(= (fly-cost loc3 loc5) 42)
	(= (fly-cost loc3 loc6) 47)
	(= (fly-cost loc3 loc7) 4)
	(= (fly-cost loc3 loc8) 23)
	(= (fly-cost loc3 loc9) 11)
	(= (fly-cost loc3 loc10) 2)
	(= (fly-cost loc4 warehouse) 5)
	(= (fly-cost loc4 loc1) 37)
	(= (fly-cost loc4 loc2) 35)
	(= (fly-cost loc4 loc3) 25)
	(= (fly-cost loc4 loc4) 0)
	(= (fly-cost loc4 loc5) 10)
	(= (fly-cost loc4 loc6) 33)
	(= (fly-cost loc4 loc7) 18)
	(= (fly-cost loc4 loc8) 28)
	(= (fly-cost loc4 loc9) 33)
	(= (fly-cost loc4 loc10) 28)
	(= (fly-cost loc5 warehouse) 38)
	(= (fly-cost loc5 loc1) 46)
	(= (fly-cost loc5 loc2) 46)
	(= (fly-cost loc5 loc3) 30)
	(= (fly-cost loc5 loc4) 9)
	(= (fly-cost loc5 loc5) 0)
	(= (fly-cost loc5 loc6) 28)
	(= (fly-cost loc5 loc7) 37)
	(= (fly-cost loc5 loc8) 45)
	(= (fly-cost loc5 loc9) 34)
	(= (fly-cost loc5 loc10) 20)
	(= (fly-cost loc6 warehouse) 20)
	(= (fly-cost loc6 loc1) 44)
	(= (fly-cost loc6 loc2) 36)
	(= (fly-cost loc6 loc3) 14)
	(= (fly-cost loc6 loc4) 30)
	(= (fly-cost loc6 loc5) 17)
	(= (fly-cost loc6 loc6) 0)
	(= (fly-cost loc6 loc7) 35)
	(= (fly-cost loc6 loc8) 5)
	(= (fly-cost loc6 loc9) 34)
	(= (fly-cost loc6 loc10) 2)
	(= (fly-cost loc7 warehouse) 17)
	(= (fly-cost loc7 loc1) 15)
	(= (fly-cost loc7 loc2) 4)
	(= (fly-cost loc7 loc3) 27)
	(= (fly-cost loc7 loc4) 14)
	(= (fly-cost loc7 loc5) 1)
	(= (fly-cost loc7 loc6) 6)
	(= (fly-cost loc7 loc7) 0)
	(= (fly-cost loc7 loc8) 21)
	(= (fly-cost loc7 loc9) 47)
	(= (fly-cost loc7 loc10) 14)
	(= (fly-cost loc8 warehouse) 37)
	(= (fly-cost loc8 loc1) 45)
	(= (fly-cost loc8 loc2) 24)
	(= (fly-cost loc8 loc3) 19)
	(= (fly-cost loc8 loc4) 4)
	(= (fly-cost loc8 loc5) 1)
	(= (fly-cost loc8 loc6) 14)
	(= (fly-cost loc8 loc7) 24)
	(= (fly-cost loc8 loc8) 0)
	(= (fly-cost loc8 loc9) 33)
	(= (fly-cost loc8 loc10) 1)
	(= (fly-cost loc9 warehouse) 48)
	(= (fly-cost loc9 loc1) 7)
	(= (fly-cost loc9 loc2) 7)
	(= (fly-cost loc9 loc3) 23)
	(= (fly-cost loc9 loc4) 33)
	(= (fly-cost loc9 loc5) 35)
	(= (fly-cost loc9 loc6) 20)
	(= (fly-cost loc9 loc7) 28)
	(= (fly-cost loc9 loc8) 22)
	(= (fly-cost loc9 loc9) 0)
	(= (fly-cost loc9 loc10) 3)
	(= (fly-cost loc10 warehouse) 17)
	(= (fly-cost loc10 loc1) 21)
	(= (fly-cost loc10 loc2) 5)
	(= (fly-cost loc10 loc3) 6)
	(= (fly-cost loc10 loc4) 38)
	(= (fly-cost loc10 loc5) 25)
	(= (fly-cost loc10 loc6) 15)
	(= (fly-cost loc10 loc7) 47)
	(= (fly-cost loc10 loc8) 40)
	(= (fly-cost loc10 loc9) 11)
	(= (fly-cost loc10 loc10) 0)
)

(:goal (and
	(drone-at drone1 warehouse)
	(drone-at drone2 warehouse)
	(drone-at drone3 warehouse)
	(drone-at drone4 warehouse)
	(drone-at drone5 warehouse)
	(drone-at drone6 warehouse)
	(carrier-at carrier1 warehouse)
	(carrier-at carrier2 warehouse)
	(carrier-at carrier3 warehouse)
	(carrier-at carrier4 warehouse)
	(carrier-at carrier5 warehouse)
	(carrier-at carrier6 warehouse)
	(human-has human1 food)
	(human-has human1 meds)
	(human-has human3 meds)
	(human-has human4 food)
	(human-has human4 meds)
	(human-has human5 food)
	(human-has human6 food)
	(human-has human8 food)
	(human-has human9 food)
	(human-has human10 food)
	))
(:metric minimize (total-time)))
