(define (problem drone_problem_d2_r2_l10_p10_c10_g10_ct2)
(:domain drone-dom)
(:objects
	drone1 - drone
	drone2 - drone
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	box1 - box
	box2 - box
	box3 - box
	box4 - box
	box5 - box
	box6 - box
	box7 - box
	box8 - box
	box9 - box
	box10 - box
	food - content
	meds - content
	human1 - human
	human2 - human
	human3 - human
	human4 - human
	human5 - human
	human6 - human
	human7 - human
	human8 - human
	human9 - human
	human10 - human
	carrier1 - carrier
	carrier2 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(carrier-at carrier1 warehouse)
	(carrier-n-boxes carrier1 n0)
	(carrier-drone-free carrier1)
	(carrier-at carrier2 warehouse)
	(carrier-n-boxes carrier2 n0)
	(carrier-drone-free carrier2)
	(drone-at drone1 warehouse)
	(drone-free drone1)
	(drone-at drone2 warehouse)
	(drone-free drone2)
	(box-at box1 warehouse)
	(box-free box1)
	(box-at box2 warehouse)
	(box-free box2)
	(box-at box3 warehouse)
	(box-free box3)
	(box-at box4 warehouse)
	(box-free box4)
	(box-at box5 warehouse)
	(box-free box5)
	(box-at box6 warehouse)
	(box-free box6)
	(box-at box7 warehouse)
	(box-free box7)
	(box-at box8 warehouse)
	(box-free box8)
	(box-at box9 warehouse)
	(box-free box9)
	(box-at box10 warehouse)
	(box-free box10)
	(box-has box1 food)
	(box-has box2 food)
	(box-has box3 meds)
	(box-has box4 meds)
	(box-has box5 meds)
	(box-has box6 meds)
	(box-has box7 meds)
	(box-has box8 meds)
	(box-has box9 meds)
	(box-has box10 meds)
	(human-at human1 loc9)
	(human-free human1)
	(human-at human2 loc6)
	(human-free human2)
	(human-at human3 loc5)
	(human-free human3)
	(human-at human4 loc8)
	(human-free human4)
	(human-at human5 loc7)
	(human-free human5)
	(human-at human6 loc3)
	(human-free human6)
	(human-at human7 loc3)
	(human-free human7)
	(human-at human8 loc8)
	(human-free human8)
	(human-at human9 loc7)
	(human-free human9)
	(human-at human10 loc7)
	(human-free human10)
	(next n0 n1)
	(next n1 n2)
	(next n2 n3)
	(next n3 n4)
	(= (fly-cost warehouse warehouse) 0)
	(= (fly-cost warehouse loc1) 25)
	(= (fly-cost warehouse loc2) 3)
	(= (fly-cost warehouse loc3) 9)
	(= (fly-cost warehouse loc4) 31)
	(= (fly-cost warehouse loc5) 43)
	(= (fly-cost warehouse loc6) 27)
	(= (fly-cost warehouse loc7) 38)
	(= (fly-cost warehouse loc8) 13)
	(= (fly-cost warehouse loc9) 39)
	(= (fly-cost warehouse loc10) 4)
	(= (fly-cost loc1 warehouse) 7)
	(= (fly-cost loc1 loc1) 0)
	(= (fly-cost loc1 loc2) 27)
	(= (fly-cost loc1 loc3) 33)
	(= (fly-cost loc1 loc4) 37)
	(= (fly-cost loc1 loc5) 6)
	(= (fly-cost loc1 loc6) 9)
	(= (fly-cost loc1 loc7) 14)
	(= (fly-cost loc1 loc8) 31)
	(= (fly-cost loc1 loc9) 30)
	(= (fly-cost loc1 loc10) 50)
	(= (fly-cost loc2 warehouse) 46)
	(= (fly-cost loc2 loc1) 39)
	(= (fly-cost loc2 loc2) 0)
	(= (fly-cost loc2 loc3) 27)
	(= (fly-cost loc2 loc4) 38)
	(= (fly-cost loc2 loc5) 37)
	(= (fly-cost loc2 loc6) 17)
	(= (fly-cost loc2 loc7) 42)
	(= (fly-cost loc2 loc8) 2)
	(= (fly-cost loc2 loc9) 41)
	(= (fly-cost loc2 loc10) 41)
	(= (fly-cost loc3 warehouse) 44)
	(= (fly-cost loc3 loc1) 2)
	(= (fly-cost loc3 loc2) 17)
	(= (fly-cost loc3 loc3) 0)
	(= (fly-cost loc3 loc4) 5)
	(= (fly-cost loc3 loc5) 45)
	(= (fly-cost loc3 loc6) 8)
	(= (fly-cost loc3 loc7) 49)
	(= (fly-cost loc3 loc8) 36)
	(= (fly-cost loc3 loc9) 4)
	(= (fly-cost loc3 loc10) 43)
	(= (fly-cost loc4 warehouse) 45)
	(= (fly-cost loc4 loc1) 14)
	(= (fly-cost loc4 loc2) 36)
	(= (fly-cost loc4 loc3) 41)
	(= (fly-cost loc4 loc4) 0)
	(= (fly-cost loc4 loc5) 35)
	(= (fly-cost loc4 loc6) 14)
	(= (fly-cost loc4 loc7) 34)
	(= (fly-cost loc4 loc8) 36)
	(= (fly-cost loc4 loc9) 23)
	(= (fly-cost loc4 loc10) 25)
	(= (fly-cost loc5 warehouse) 10)
	(= (fly-cost loc5 loc1) 4)
	(= (fly-cost loc5 loc2) 48)
	(= (fly-cost loc5 loc3) 43)
	(= (fly-cost loc5 loc4) 31)
	(= (fly-cost loc5 loc5) 0)
	(= (fly-cost loc5 loc6) 30)
	(= (fly-cost loc5 loc7) 1)
	(= (fly-cost loc5 loc8) 22)
	(= (fly-cost loc5 loc9) 3)
	(= (fly-cost loc5 loc10) 13)
	(= (fly-cost loc6 warehouse) 13)
	(= (fly-cost loc6 loc1) 31)
	(= (fly-cost loc6 loc2) 14)
	(= (fly-cost loc6 loc3) 23)
	(= (fly-cost loc6 loc4) 45)
	(= (fly-cost loc6 loc5) 5)
	(= (fly-cost loc6 loc6) 0)
	(= (fly-cost loc6 loc7) 17)
	(= (fly-cost loc6 loc8) 5)
	(= (fly-cost loc6 loc9) 11)
	(= (fly-cost loc6 loc10) 39)
	(= (fly-cost loc7 warehouse) 14)
	(= (fly-cost loc7 loc1) 7)
	(= (fly-cost loc7 loc2) 48)
	(= (fly-cost loc7 loc3) 13)
	(= (fly-cost loc7 loc4) 47)
	(= (fly-cost loc7 loc5) 13)
	(= (fly-cost loc7 loc6) 21)
	(= (fly-cost loc7 loc7) 0)
	(= (fly-cost loc7 loc8) 37)
	(= (fly-cost loc7 loc9) 46)
	(= (fly-cost loc7 loc10) 44)
	(= (fly-cost loc8 warehouse) 46)
	(= (fly-cost loc8 loc1) 42)
	(= (fly-cost loc8 loc2) 2)
	(= (fly-cost loc8 loc3) 36)
	(= (fly-cost loc8 loc4) 31)
	(= (fly-cost loc8 loc5) 21)
	(= (fly-cost loc8 loc6) 30)
	(= (fly-cost loc8 loc7) 24)
	(= (fly-cost loc8 loc8) 0)
	(= (fly-cost loc8 loc9) 38)
	(= (fly-cost loc8 loc10) 42)
	(= (fly-cost loc9 warehouse) 35)
	(= (fly-cost loc9 loc1) 13)
	(= (fly-cost loc9 loc2) 12)
	(= (fly-cost loc9 loc3) 19)
	(= (fly-cost loc9 loc4) 38)
	(= (fly-cost loc9 loc5) 8)
	(= (fly-cost loc9 loc6) 27)
	(= (fly-cost loc9 loc7) 3)
	(= (fly-cost loc9 loc8) 40)
	(= (fly-cost loc9 loc9) 0)
	(= (fly-cost loc9 loc10) 16)
	(= (fly-cost loc10 warehouse) 7)
	(= (fly-cost loc10 loc1) 28)
	(= (fly-cost loc10 loc2) 45)
	(= (fly-cost loc10 loc3) 28)
	(= (fly-cost loc10 loc4) 2)
	(= (fly-cost loc10 loc5) 12)
	(= (fly-cost loc10 loc6) 3)
	(= (fly-cost loc10 loc7) 21)
	(= (fly-cost loc10 loc8) 2)
	(= (fly-cost loc10 loc9) 38)
	(= (fly-cost loc10 loc10) 0)
)

(:goal (and
	(drone-at drone1 warehouse)
	(drone-at drone2 warehouse)
	(carrier-at carrier1 warehouse)
	(carrier-at carrier2 warehouse)
	(human-has human1 meds)
	(human-has human2 meds)
	(human-has human3 meds)
	(human-has human4 meds)
	(human-has human7 meds)
	(human-has human8 food)
	(human-has human8 meds)
	(human-has human9 meds)
	(human-has human10 food)
	(human-has human10 meds)
	))
)
