(define (problem drone_problem_d4_r4_l10_p10_c10_g10_ct2)
(:domain drone-dom)
(:objects
	drone1 - drone
	drone2 - drone
	drone3 - drone
	drone4 - drone
	warehouse - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
	loc10 - location
	box1 - box
	box2 - box
	box3 - box
	box4 - box
	box5 - box
	box6 - box
	box7 - box
	box8 - box
	box9 - box
	box10 - box
	food - content
	meds - content
	human1 - human
	human2 - human
	human3 - human
	human4 - human
	human5 - human
	human6 - human
	human7 - human
	human8 - human
	human9 - human
	human10 - human
	carrier1 - carrier
	carrier2 - carrier
	carrier3 - carrier
	carrier4 - carrier
	n0 n1 n2 n3 n4 - num
)

(:init
	(carrier-at carrier1 warehouse)
	(carrier-n-boxes carrier1 n0)
	(carrier-at carrier2 warehouse)
	(carrier-n-boxes carrier2 n0)
	(carrier-at carrier3 warehouse)
	(carrier-n-boxes carrier3 n0)
	(carrier-at carrier4 warehouse)
	(carrier-n-boxes carrier4 n0)
	(drone-at drone1 warehouse)
	(drone-free drone1)
	(drone-at drone2 warehouse)
	(drone-free drone2)
	(drone-at drone3 warehouse)
	(drone-free drone3)
	(drone-at drone4 warehouse)
	(drone-free drone4)
	(box-at box1 warehouse)
	(box-free box1)
	(box-at box2 warehouse)
	(box-free box2)
	(box-at box3 warehouse)
	(box-free box3)
	(box-at box4 warehouse)
	(box-free box4)
	(box-at box5 warehouse)
	(box-free box5)
	(box-at box6 warehouse)
	(box-free box6)
	(box-at box7 warehouse)
	(box-free box7)
	(box-at box8 warehouse)
	(box-free box8)
	(box-at box9 warehouse)
	(box-free box9)
	(box-at box10 warehouse)
	(box-free box10)
	(box-has box1 food)
	(box-has box2 meds)
	(box-has box3 meds)
	(box-has box4 meds)
	(box-has box5 meds)
	(box-has box6 meds)
	(box-has box7 meds)
	(box-has box8 meds)
	(box-has box9 meds)
	(box-has box10 meds)
	(human-at human1 loc6)
	(human-at human2 loc8)
	(human-at human3 loc1)
	(human-at human4 loc4)
	(human-at human5 loc3)
	(human-at human6 loc7)
	(human-at human7 loc7)
	(human-at human8 loc4)
	(human-at human9 loc8)
	(human-at human10 loc9)
	(next n0 n1)
	(next n1 n2)
	(next n2 n3)
	(next n3 n4)
	(= (fly-cost warehouse warehouse) 0)
	(= (fly-cost warehouse loc1) 12)
	(= (fly-cost warehouse loc2) 38)
	(= (fly-cost warehouse loc3) 25)
	(= (fly-cost warehouse loc4) 34)
	(= (fly-cost warehouse loc5) 19)
	(= (fly-cost warehouse loc6) 35)
	(= (fly-cost warehouse loc7) 16)
	(= (fly-cost warehouse loc8) 10)
	(= (fly-cost warehouse loc9) 29)
	(= (fly-cost warehouse loc10) 26)
	(= (fly-cost loc1 warehouse) 17)
	(= (fly-cost loc1 loc1) 0)
	(= (fly-cost loc1 loc2) 34)
	(= (fly-cost loc1 loc3) 14)
	(= (fly-cost loc1 loc4) 41)
	(= (fly-cost loc1 loc5) 9)
	(= (fly-cost loc1 loc6) 16)
	(= (fly-cost loc1 loc7) 17)
	(= (fly-cost loc1 loc8) 5)
	(= (fly-cost loc1 loc9) 40)
	(= (fly-cost loc1 loc10) 32)
	(= (fly-cost loc2 warehouse) 26)
	(= (fly-cost loc2 loc1) 11)
	(= (fly-cost loc2 loc2) 0)
	(= (fly-cost loc2 loc3) 41)
	(= (fly-cost loc2 loc4) 21)
	(= (fly-cost loc2 loc5) 45)
	(= (fly-cost loc2 loc6) 27)
	(= (fly-cost loc2 loc7) 5)
	(= (fly-cost loc2 loc8) 44)
	(= (fly-cost loc2 loc9) 26)
	(= (fly-cost loc2 loc10) 37)
	(= (fly-cost loc3 warehouse) 35)
	(= (fly-cost loc3 loc1) 24)
	(= (fly-cost loc3 loc2) 37)
	(= (fly-cost loc3 loc3) 0)
	(= (fly-cost loc3 loc4) 30)
	(= (fly-cost loc3 loc5) 3)
	(= (fly-cost loc3 loc6) 48)
	(= (fly-cost loc3 loc7) 17)
	(= (fly-cost loc3 loc8) 28)
	(= (fly-cost loc3 loc9) 5)
	(= (fly-cost loc3 loc10) 3)
	(= (fly-cost loc4 warehouse) 44)
	(= (fly-cost loc4 loc1) 47)
	(= (fly-cost loc4 loc2) 38)
	(= (fly-cost loc4 loc3) 17)
	(= (fly-cost loc4 loc4) 0)
	(= (fly-cost loc4 loc5) 13)
	(= (fly-cost loc4 loc6) 18)
	(= (fly-cost loc4 loc7) 35)
	(= (fly-cost loc4 loc8) 44)
	(= (fly-cost loc4 loc9) 15)
	(= (fly-cost loc4 loc10) 37)
	(= (fly-cost loc5 warehouse) 36)
	(= (fly-cost loc5 loc1) 22)
	(= (fly-cost loc5 loc2) 48)
	(= (fly-cost loc5 loc3) 12)
	(= (fly-cost loc5 loc4) 46)
	(= (fly-cost loc5 loc5) 0)
	(= (fly-cost loc5 loc6) 4)
	(= (fly-cost loc5 loc7) 39)
	(= (fly-cost loc5 loc8) 49)
	(= (fly-cost loc5 loc9) 30)
	(= (fly-cost loc5 loc10) 34)
	(= (fly-cost loc6 warehouse) 6)
	(= (fly-cost loc6 loc1) 4)
	(= (fly-cost loc6 loc2) 43)
	(= (fly-cost loc6 loc3) 34)
	(= (fly-cost loc6 loc4) 8)
	(= (fly-cost loc6 loc5) 39)
	(= (fly-cost loc6 loc6) 0)
	(= (fly-cost loc6 loc7) 28)
	(= (fly-cost loc6 loc8) 27)
	(= (fly-cost loc6 loc9) 37)
	(= (fly-cost loc6 loc10) 16)
	(= (fly-cost loc7 warehouse) 26)
	(= (fly-cost loc7 loc1) 44)
	(= (fly-cost loc7 loc2) 1)
	(= (fly-cost loc7 loc3) 29)
	(= (fly-cost loc7 loc4) 6)
	(= (fly-cost loc7 loc5) 7)
	(= (fly-cost loc7 loc6) 15)
	(= (fly-cost loc7 loc7) 0)
	(= (fly-cost loc7 loc8) 39)
	(= (fly-cost loc7 loc9) 10)
	(= (fly-cost loc7 loc10) 48)
	(= (fly-cost loc8 warehouse) 7)
	(= (fly-cost loc8 loc1) 30)
	(= (fly-cost loc8 loc2) 8)
	(= (fly-cost loc8 loc3) 46)
	(= (fly-cost loc8 loc4) 23)
	(= (fly-cost loc8 loc5) 20)
	(= (fly-cost loc8 loc6) 3)
	(= (fly-cost loc8 loc7) 17)
	(= (fly-cost loc8 loc8) 0)
	(= (fly-cost loc8 loc9) 40)
	(= (fly-cost loc8 loc10) 43)
	(= (fly-cost loc9 warehouse) 4)
	(= (fly-cost loc9 loc1) 48)
	(= (fly-cost loc9 loc2) 2)
	(= (fly-cost loc9 loc3) 31)
	(= (fly-cost loc9 loc4) 3)
	(= (fly-cost loc9 loc5) 29)
	(= (fly-cost loc9 loc6) 1)
	(= (fly-cost loc9 loc7) 38)
	(= (fly-cost loc9 loc8) 28)
	(= (fly-cost loc9 loc9) 0)
	(= (fly-cost loc9 loc10) 29)
	(= (fly-cost loc10 warehouse) 6)
	(= (fly-cost loc10 loc1) 35)
	(= (fly-cost loc10 loc2) 26)
	(= (fly-cost loc10 loc3) 9)
	(= (fly-cost loc10 loc4) 35)
	(= (fly-cost loc10 loc5) 5)
	(= (fly-cost loc10 loc6) 16)
	(= (fly-cost loc10 loc7) 34)
	(= (fly-cost loc10 loc8) 5)
	(= (fly-cost loc10 loc9) 30)
	(= (fly-cost loc10 loc10) 0)
)

(:goal (and
	(drone-at drone1 warehouse)
	(drone-at drone2 warehouse)
	(drone-at drone3 warehouse)
	(drone-at drone4 warehouse)
	(carrier-at carrier1 warehouse)
	(carrier-at carrier2 warehouse)
	(carrier-at carrier3 warehouse)
	(carrier-at carrier4 warehouse)
	(human-has human1 meds)
	(human-has human2 meds)
	(human-has human3 meds)
	(human-has human4 meds)
	(human-has human5 meds)
	(human-has human6 food)
	(human-has human7 meds)
	(human-has human8 meds)
	(human-has human9 meds)
	(human-has human10 meds)
	))
)
